### ISSUE TITLE
Add a way to pass a base path aka 'basename' to createHistory?

### ISSUE THREAD

**Issue by adailey14** [halt-hammerzeit/react-isomorphic-render#20]
I need to add a base path to react-isomorphic-render, so I can mount it at a subdirectory of a large app and it won't get confused.

history.js has a basename option for this reason: https://github.com/mjackson/history#using-a-base-url

The relevant place in your code to pass it would be something like source/redux/store.js (around line 101):

```
	store_enhancers.push
	(
		// `redux-router` middleware
		// (redux-router keeps react-router state in Redux)
		reduxReactRouter
		({
			getRoutes : create_routes,
			createHistory: (...historyArgs) => createHistory({ ...historyArgs, basename: options.baseName || '' })
		}),

		// Ajax and @preload middleware (+ optional others)
		applyMiddleware(...middlewares)
	)
```

Would it be possible to add something like this?

**Comment by halt-hammerzeit** [comment]
Try the new version (5.0.5), that should to it.
https://github.com/halt-hammerzeit/react-isomorphic-render/commit/a5caab64d86cd760af4522705ab6939c46940556

**Comment by adailey14** [comment]
Thanks! This is working to pass in the options. 

Unfortunately, it looks like using "basename" as an option was added in history.js version 3.0, and this project is using history 2.0.1. In 2.0.1, you had to call a useBasename enhancer function: https://github.com/mjackson/history/blob/v2.0.1/docs/BasenameSupport.md.

Do you think you could update the version of history.js (latest version is 4.3)? Or else put an option that lets me modify history, like modifyHistory: history => useBasename('/mypath', history).

**Comment by halt-hammerzeit** [comment]
`redux-router` doesn't support history `3.x`.
https://github.com/acdlite/redux-router/issues/259
So does `react-router-redux`:
https://github.com/reactjs/react-router-redux/blob/master/package.json#L59

`useBasename` seems a viable solution and I implemented it in the latest version (`5.0.6`).

They also say in the docs that:

```
Basename-enhanced histories also automatically prepend the basename to paths used in push, replace, createPath, and createHref.
```

I've taken some measures to support that.
If you have any issues with redirecting and `basename` then that can be fixed too.

(gone walking in a park)

**Comment by adailey14** [comment]
Aha, ok didn't realize the version constraints. Thanks for adding useBasename, it seems to work great so far. I'll let you know if I run into any problems with redirecting, so far so good.

**Comment by adailey14** [comment]
I'm having trouble getting the history: { options: { basename: '/mypath' }} setting to work. It doesn't seem to be recognized in react-router the way it used to. I know a lot has changed since then. Do you have any ideas where I should start debugging?

**Comment by halt-hammerzeit** [comment]
So what you're saying is that it works the old way but it doesn't work the new way?

**Comment by adailey14** [comment]
I can't get it to work in any way using the latest version.

It used to work when I was on an older version of react-isomorphic-render
and universal-webpack. I'm digging into some of the code, but wondering if
I need to do anything special to "wrap" the history object used by
react-router for example? I saw you added an option for doing that next to
the options: { basename } part.

I also saw in this issue we had a reference to useBasepath - not sure if
that is still part of the package somewhere?

**Comment by halt-hammerzeit** [comment]
Well, you could `console.log()` the `options` here
https://github.com/halt-hammerzeit/react-isomorphic-render/blob/30b1c00a543560ba6042bc7f0318db5de6745f2a/source/client.js#L95
It should add `useBasename` by default but you could double-check that too by re-applying `useBasename()` there.

**Comment by adailey14** [comment]
Hmm ok, I tried that but I don't see the logging get triggered at all.

I am hitting an error like this in the browser, I wonder if this error is happening before the client side history is created?:
```
Uncaught (in promise) Error: No <Route/> matches URL "/mybasepath/otherpath/"
 at match.js:52
    at match.js:67
    at createTransitionManager.js:63
    at next (AsyncUtils.js:52)
    at loopAsync (AsyncUtils.js:56)
    at matchRoutes (matchRoutes.js:253)
    at Object.match (createTransitionManager.js:57)
    at match (match.js:56)
    at match.js:35
    at Promise (<anonymous>)
```

**Comment by halt-hammerzeit** [comment]
You should edit the file in the `build` folder and it will output to Node.js console.
First history is created, then it matches routes.

**Comment by halt-hammerzeit** [comment]
Oh, it's client side, and you're hitting the error on server.
I guess the server doesn't have `useBasename` activated maybe.

**Comment by halt-hammerzeit** [comment]
No, seems that it does have `useBasename` added on the server side too
https://github.com/halt-hammerzeit/react-isomorphic-render/blob/30b1c00a543560ba6042bc7f0318db5de6745f2a/source/page-server/render.js#L7
Still you could double-check that by reapplying it.
Also you may `console.log` the options on the server.

**Comment by halt-hammerzeit** [comment]
My guess is that the bug is on this line:
https://github.com/halt-hammerzeit/react-isomorphic-render/blob/30b1c00a543560ba6042bc7f0318db5de6745f2a/source/page-server/render.js#L85

```js
history = create_history(createHistory, request.url, settings.history, parameters, true)
```

Perhaps it should be changed to:
```js
history = create_history(createHistory, request.url, settings.history.options, parameters, true)
```

Try that

**Comment by adailey14** [comment]
It seems like that fixes things on the server (I used to "fix" this on the server by proxying from /basepath in the "webserver" to "/" in the renderingService, so the renderingService never saw the basepath). After changing the line you specified the server works even when I proxy from ("/basepath" to "/basepath"). However the client still gives the Error: No <Route/> matches URL. Is history "created" on the client somewhere different?

**Comment by halt-hammerzeit** [comment]
Yes, it is created differently on client and server.
Since the server is fixed, here's where it is created on the client:
https://github.com/halt-hammerzeit/react-isomorphic-render/blob/30b1c00a543560ba6042bc7f0318db5de6745f2a/source/redux/client/client.js#L91
And seems that it's the same bug as the server-side one.
Try it.

**Comment by adailey14** [comment]
Hmm I tried changing that line, but still getting the same error on the client.

**Comment by halt-hammerzeit** [comment]
Are you changing the `es6` folder now?
Because in case of Webpack 2 it uses `es6` instead of `build`.

**Comment by adailey14** [comment]
Oh, no I was changing it in the build folder! I didn't realize that, let me try it.

**Comment by adailey14** [comment]
Ok so the change seems to be taking effect now. I've gone from seeing the No <Route/> matches URL "/mybasepath/otherpath/" directly in the browser console, to seeing the same error as a preload error. This might be something in my code though - I will continue to investigate.

**Comment by halt-hammerzeit** [comment]
> to seeing the same error as a preload error

You mean inside the `catch` function?
It shouldn't output an error at all in case of a non-match - it should redirect to the `<DefaultRoute/>` which is a not found page.
But I assume you removed that for testing.

**Comment by adailey14** [comment]
Yes I put my own console.log inside the preload catch so I could see what's happening.

**Comment by adailey14** [comment]
Hmm so I don't see anything obvious in my code causing this (I though maybe I was trying to redirect to a bad path or something). Seems more likely that maybe some of the internal preloading code is doing some match logic to figure out which preloaders to run - and that is not using the basepath?

**Comment by halt-hammerzeit** [comment]
I'm gonna try simulating basepath in my own project.

**Comment by adailey14** [comment]
Ok thanks. I see some code in es6/history.js where there is a history_options, and it is used as history_options.basename as well as history_options.wrap. So maybe that should be history_options.options.basename? But not sure if the parameters are getting normalized somewhere else first? I will play log some things to find out.

**Comment by adailey14** [comment]
Nope... those history_options look ok, so it's not that.

**Comment by halt-hammerzeit** [comment]
So, I'm first seeing a "Page not found" page but I'm redirected to the correct page shortly thereafter.

**Comment by adailey14** [comment]
Hmm that sounds kindof the opposite of what I'm seeing. Like your server side render doesn't find the path, but then your client side finds it?

**Comment by halt-hammerzeit** [comment]
Ok, I tested it and it works in my case (completely, without any not found pages)

```js


  history: {
    options: {
      basename: '/test'
    }
  },
```

Reinstall the latest version and try again because this might be side effects of your module code edits

**Comment by adailey14** [comment]
Ok thanks I will try

**Comment by adailey14** [comment]
Well... I am still seeing that error in the preload catch on the initial page load. But everything works fine after that (if I catch that error and don't do anything with it). I also have some redirects I am doing in preload that don't seem to work. For example I redirect to "/path", hoping that it would redirect the page to "/basepath/path", but it tries to go to "/path". I can work around that, but seems like something fishy is still going on in the preloading realm.

**Comment by halt-hammerzeit** [comment]
You can make up a simple sample project and if the issues you described manifest themselves in it I can take a look

**Comment by halt-hammerzeit** [comment]
E.g. you can fork the example project and reproduce any potential bugs there:
https://github.com/halt-hammerzeit/webpack-react-redux-isomorphic-render-example

**Comment by adailey14** [comment]
Yep sounds good I will try to do that. Thanks as always for your help

**Comment by adailey14** [comment]
Ok, I was able to reproduce it. It looks simple but took me a long time to find - ended up digging pretty deep into react-router matching code. 
Reproduction is here:
https://github.com/adailey14/webpack-react-redux-isomorphic-render-example

All I had to do to reproduce was add the basename option, and remove the wildcard "*" route from routes.js. From what I can tell, you were not seeing the same error before because the client side preloading code was matching /basename to the * route, and so not complaining (but likely would not be preloading the correct data?). Once you remove that route you should see the same error in the console that I was seeing.

Let me know if you see it too. I don't know how to fix it...

**Comment by halt-hammerzeit** [comment]
I see now.
Fixed, see the related commit and install the latest version.

**Comment by adailey14** [comment]
Awesome thank you!

**Comment by adailey14** [comment]
I was just able to test this and it works. One other issue happening is when I redirect from preload it doesn't automatically use the basename, and it probably should:

```
import { preload, redirect, Link } from 'react-isomorphic-render';

@preload(({ dispatch, getState }) => {
  const { authentication } = getState();
  if (authentication.isAuthenticated) {
    // This redirect goes to /dashboard, instead of /basename/dashboard
    return dispatch(redirect('/dashboard/'));
  }
  return Promise.resolve();
})
export default class Login extends Component {
  ...
  render() {
    return (
      <div>
        <Link to="/dashboard/">This link to the dashboard actually links to /basename/dashboard</Link>
      </div>
    );
  }
}
```

The preload redirect sends me to http://localhost:3080/dashboard, which is not a valid route. I want it to redirect to http://localhost:3080/basename/dashboard, the same way the <Link> does. Not sure if this only happens in preload or anywhere redirect is used?

**Comment by halt-hammerzeit** [comment]
Is this happening only on the server or is it happening on both client and server

**Comment by adailey14** [comment]
I am seeing it happen on the server at the moment. I can test if it is happening on client as well, will let you know.

**Comment by adailey14** [comment]
Yes it seems it is only happening on the server, not on the client

**Comment by halt-hammerzeit** [comment]
You can modify your example project fork to illustrate the error and I can have a look

**Comment by adailey14** [comment]
Ok will do, thanks

**Comment by adailey14** [comment]
Ok I just added a commit showing what happens. If you visit http://localhost:3000/basename, it will redirect you to http://localhost:3000/users instead of http://localhost:3000/basename/users.

Note - I made the webserver proxy /basename to /basename to better illustrate the issue. If I don't do that, the rendering server will respond to both /basename/users and /users the same way. I'm not sure if it should do that, or only respond to /basename/users. It doesn't matter in my use case because I am proxying / mounting at the basename, so requests without the basename will not reach the rendering service.

**Comment by adailey14** [comment]
Link to commit: https://github.com/adailey14/webpack-react-redux-isomorphic-render-example/commit/64fa3d08e14e9f81930d6ad9a39835e7c0c2dc38

**Comment by halt-hammerzeit** [comment]
Seems to have been fixed in the latest release

**Comment by adailey14** [comment]
This is great, thank you! Seems to work now everywhere. I'll let you know
if I run into anything else. Thanks for supporting my base name usage,
maybe I'm the only one using it

**Comment by halt-hammerzeit** [comment]
I guess you are...
At the same time I can't say "we won't support this" because having people using your library in real-life is important for testing its overall survivability and finding bugs / missing features / wrong design choices / bottlenecks.
And the recent `basename` hassle introduced some noise to the code so I took some time to redesign it a bit and released `v11` of this library which you can have a look at if you will (since you're in the process of upgrading to `v10`, maybe it would make sense to upgrade straight to `v11`).
The changes are renaming of `catch()` (former `preload.catch()`) to `error()` and rewriting the `basename` logic.
I tested it in various cases and it seems to work.

**Comment by adailey14** [comment]
Sounds good I will try v11. I appreciate your philosophy.
