### ISSUE TITLE
Hook to inject render-dependent data for SSR? 

### ISSUE THREAD

**Issue by benoneal** [halt-hammerzeit/react-isomorphic-render#35]
`Helmet`and `redux` stores are two examples of render-dependent data, in that they require a full render pass through `renderToString` to populate the store | enable `rewind`. These are currently being used to that effect in this project, but there aren't any hooks exposed to interact with this step of the render pipeline. 

I'm using a css-in-js library which offers the same functionality: a render pass will populate its stylesheets, and you can call `getCss` to render a string version into the `<head>` for SSR. 

I'm having trouble finding any hooks available that would enable me to do this. My best guess, the `html.head()` method, is unfortunately called before `renderToString`. 

If there's somewhere I could inject this during SSR, please let me know. Otherwise, could you expose a post-render method to allow this sort of pattern?

**Comment by halt-hammerzeit** [comment]
I didn't understand what you're trying to say here

**Comment by halt-hammerzeit** [comment]
I think I get what you mean.

https://github.com/halt-hammerzeit/react-isomorphic-render/blob/122c2e82ef9a41ed971cc4f8edc8e7c7e146bf14/source/page-server/render.js#L68-L77
`head` is evaluated before the page is rendered:
https://github.com/halt-hammerzeit/react-isomorphic-render/blob/e55b9a29effb956f389f961a8b3080bb83448820/source/redux/server/render.js#L76

I could move `head` evaluation to `render_webpage()`:
https://github.com/halt-hammerzeit/react-isomorphic-render/blob/122c2e82ef9a41ed971cc4f8edc8e7c7e146bf14/source/page-server/render.js#L132
In this case it will be evaluated after the React page has been rendered.

Would that solve this issue.
Or did you choose a different approach.

**Comment by benoneal** [comment]
Yeah deferring the `head` evaluation would work great.

**Comment by halt-hammerzeit** [comment]
Done in https://github.com/halt-hammerzeit/react-isomorphic-render/commit/1c2ad469e03535fcd72232012e218d47a4f94d98

**Comment by halt-hammerzeit** [comment]
All this rewind machinery is not thread safe by the way.
https://github.com/nfl/react-helmet/issues/240
So if using alternative react renderers (like streaming ones) all those "side effects" won't work.

**Comment by benoneal** [comment]
It seems this still isn't resolved. Looking at the code, it's an easy fix. 

https://github.com/halt-hammerzeit/react-isomorphic-render/blob/master/source/page-server/render.js:151 

`content` needs to be resolved at line 125, right before `head` is executed.

Like this: 
```
render_webpage(content)
		{
				...

				// Normalize `html` parameters
                                content = render === false ? normalize_markup(loading) : (content && ReactDOM.renderToString(content))
				head       = normalize_markup(typeof head       === 'function' ? head      (path, parameters) : head)
				...

				// Render the HTML
				return Html
				({
					...parameters,
					extension_javascript: typeof extension_javascript === 'function' ? extension_javascript() : extension_javascript,
					assets,
					locale,
					locale_messages_json: messagesJSON,
					head,
					body_start,
					body_end,
					authentication_token,
					content
				})
		}
```

**Comment by halt-hammerzeit** [comment]
Yeah, that will do.
Released `react-isomorphic-render@10.2.9`

**Comment by benoneal** [comment]
That appears to have done the trick :+1:
